# Generated by Django 3.0 on 2021-07-07 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_article_report'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Report',
            new_name='User',
        ),
    ]
