# Generated by Django 3.0 on 2021-07-07 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_auto_20210707_0723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='article',
            new_name='articles',
        ),
    ]
