# Generated by Django 3.0 on 2021-07-07 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_auto_20210707_0749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='articles',
        ),
        migrations.AddField(
            model_name='user',
            name='articles',
            field=models.ForeignKey(default=23, on_delete=django.db.models.deletion.CASCADE, related_name='reporter', to='school.Article'),
            preserve_default=False,
        ),
    ]
