# Generated by Django 3.0 on 2021-07-07 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_auto_20210707_1005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='articles',
            new_name='arti',
        ),
    ]
