# Generated by Django 3.0 on 2021-07-07 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_auto_20210707_1007'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Userxd',
        ),
    ]
