# Generated by Django 3.0 on 2021-07-07 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_auto_20210707_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=20)),
                ('arti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporter', to='school.Article')),
            ],
        ),
        migrations.DeleteModel(
            name='Userxd',
        ),
    ]
