# Generated by Django 3.0.5 on 2021-08-20 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm_api', '0002_auto_20210820_0451'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('books', models.ManyToManyField(to='orm_api.Book')),
            ],
        ),
    ]
